import Head from 'next/head';
import { Roboto } from 'next/font/google';
import { Main, TextWrapper } from '@/styles/Home.styles';
import { IllustrationSmallScreen } from '@/components/images/svgs/IllustrationSmallScreen/IllustrationSmallScreen';
import { Banner } from '@/components/Banner/Banner';
import { List } from '@/components/List/List';
import { useForm, SubmitHandler } from 'react-hook-form';
import { InputEmail } from '@/components/Form/InputEmail/InputEmail';
import { useFormData } from '../../contexts';
import { SuccessMessage } from '@/components/SuccessMessage/SuccessMessage';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

type Inputs = {
  example: string;
  exampleRequired: string;
};

export default function Home() {
  const { successSubmission } = useFormData();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main className={`${roboto.className}`}>
        {successSubmission ? (
          <SuccessMessage />
        ) : (
          <>
            <IllustrationSmallScreen />
            <TextWrapper>
              <Banner textLevel={'h1'}>Stay Updated!</Banner>
              <Banner textLevel={'p'}>
                Join 60,000+ product managers receiving monthly updates on:
              </Banner>
              <List />
              <InputEmail />
            </TextWrapper>
          </>
        )}
      </Main>
    </>
  );
}

// className={`${styles.main} ${roboto.className}`
